### ISSUE TITLE
Syntax error on PHP 5.3

### ISSUE THREAD

**Issue by youthkee** [fumikito/wp-readme#3]
I used wp-readme with travis2wpplugin and failed to generate readme.txt and deploy to svn repository.
It seems that occur a syntax error with "phpenv global 5.3" on .travis.yml.

https://travis-ci.org/littlebirdjp/floating-top-link/jobs/199234020

Then, I change PHP version from 5.3 to 5.6 by reference to HameSlack, it works well.
So, it might be better to write supported PHP version on README.md, because an example of travis2wpplugin is described as "PHP 5.3".

https://github.com/miya0001/travis2wpplugin

**Comment by fumikito** [comment]
Thank you @youthkee !
